/* Baza ćwiczeń — opisy PL + darmowe materiały wideo (linki do YouTube).
   Maciej: przy ćwiczeniu możesz podmienić `video` na konkretny film (URL YouTube).
   Zasada: linki prowadzą do wyszukiwań/kanałów, więc nie „psują się” jak pojedyncze filmy. */
const EXERCISE_LIBRARY_URL = "https://www.youtube.com/@e3rehabexerciselibrary";
const ytSearch = (q) => `https://www.youtube.com/results?search_query=${encodeURIComponent(q)}`;

const EXERCISES = [
  // ---- KOLANO ----
  { id: "quad-set", yt: '5TUK4uT2nnw', area: "Kolano", name: "Napinanie czworogłowego (quad set)",
    goal: "Pierwsze „budzenie” mięśnia po urazie / operacji; pełny wyprost kolana.",
    steps: ["Siad z wyprostowaną nogą, mały ręcznik pod kolanem.", "Dociśnij tył kolana w ręcznik, palce do siebie.", "Przytrzymaj 10 s, rozluźnij. Powtórz."],
    dosage: "10 × 10 s, kilka razy dziennie", contra: "Ostry, narastający ból; gorączka pooperacyjna — skontaktuj się z lekarzem.",
    video: 'https://www.youtube.com/watch?v=5TUK4uT2nnw', videoLabel: 'Quad Set — pokaz (TSAOG)' },
  { id: "slr", yt: 'EWGR5mTPzsU', area: "Kolano", name: "Unoszenie wyprostowanej nogi",
    goal: "Siła czworogłowego bez obciążania stawu.",
    steps: ["Leżenie na plecach, druga noga zgięta.", "Napnij udo, unieś nogę ~30 cm.", "Opuszczaj powoli 3 s."],
    dosage: "3 × 10 na stronę", contra: "Ból w pachwinie, „strzelanie” w kolanie — zmniejsz zakres.",
    video: 'https://www.youtube.com/watch?v=EWGR5mTPzsU', videoLabel: 'Straight Leg Raise — Margaret Martin, PT' },
  { id: "tke", yt: 'WEcLkuvcMZc', area: "Kolano", name: "Doprost końcowy z gumą (TKE)",
    goal: "Końcowy wyprost i kontrola kolana w staniu.",
    steps: ["Guma za kolanem na wysokości stawu.", "Lekki przysiad, potem doprostuj kolano w gumę.", "Przytrzymaj 2 s."],
    dosage: "3 × 12", contra: "Niestabilność / uciekanie kolana — wróć do quad set.",
    video: 'https://www.youtube.com/watch?v=WEcLkuvcMZc', videoLabel: 'Banded TKE — instruktaż' },
  { id: "bridge", yt: 'KI6fjDqGZh4', area: "Kolano", name: "Mostek biodrowy",
    goal: "Pośladki i tył uda — odciążenie kolana.",
    steps: ["Leżenie, stopy na podłodze.", "Unieś biodra do linii kolana–bark.", "Przytrzymaj 3 s, opuść."],
    dosage: "3 × 12", contra: "Ból lędźwi — zmniejsz wysokość.",
    video: 'https://www.youtube.com/watch?v=KI6fjDqGZh4', videoLabel: 'Glute Bridge — 3 kroki' },
  { id: "stepup", yt: '2g6G_GpsBoc', area: "Kolano", name: "Wejścia na stopień",
    goal: "Siła funkcjonalna: schody, chodzenie.",
    steps: ["Stopień 15–20 cm, wolno wejdź chorą nogą.", "Dostaw drugą, zejdź tą samą.", "Kolano nad stopą, nie ucieka do środka."],
    dosage: "3 × 8 na stronę", contra: "Obrzęk narastający po sesji — niższy stopień.",
    video: 'https://www.youtube.com/watch?v=2g6G_GpsBoc', videoLabel: 'Step Ups — Physio Logic NYC' },
  { id: "retro-walk", yt: 'TLGgc3NBNjY', area: "Kolano", name: "Chodzenie tyłem (retro-walking)",
    goal: "Wyprost kolana i kontrola chodu.",
    steps: ["Płaski, pusty odcinek 10–20 m.", "Małe kroki tyłem, pięta → palce.", "Napinaj udo przy każdym kroku."],
    dosage: "10–20 min dziennie / co drugi dzień", contra: "Zawroty głowy, niestabilność — tylko z asekuracją.",
    video: 'https://www.youtube.com/watch?v=TLGgc3NBNjY', videoLabel: 'Chodzenie tyłem — fizjoterapeuta', videoLabel: "O metodzie: retro-walking" },
  // ---- BARK ----
  { id: "codman", yt: 'd_w7K2ntVCA', area: "Bark", name: "Wahadełka Codmana",
    goal: "Odciążenie i ukrwienie bolesnego barku.",
    steps: ["Opad tułowia, zdrowa ręka na stole.", "Chora luźno zwisa.", "Małe kółka 30–60 s w każdą stronę."],
    dosage: "2–3 × dziennie po 1–2 min", contra: "Świeże zwichnięcie / złamanie bez zgody lekarza.",
    video: 'https://www.youtube.com/watch?v=d_w7K2ntVCA', videoLabel: 'Wahadełka Codmana — Rehab and Revive' },
  { id: "scaption", yt: 'N3P7rp7bCYc', area: "Bark", name: "Unoszenie w płaszczyźnie łopatki",
    goal: "Stożek rotatorów bez konfliktu.",
    steps: ["Lekki ciężar / guma, kciuki do góry.", "Unieś ręce ~30° do przodu od linii ciała.", "Tylko do poziomu barków."],
    dosage: "3 × 10", contra: "Ból łukowy 60–120° — zmniejsz ciężar/zakres.",
    video: 'https://www.youtube.com/watch?v=N3P7rp7bCYc', videoLabel: 'Dumbbell Scaption Raise' },
  { id: "er-band", yt: 'y8WKcz0vqzg', area: "Bark", name: "Rotacja zewnętrzna z gumą",
    goal: "Stabilizatory barku (podgrzebieniowy).",
    steps: ["Łokieć przy żebrach, zgięty 90°.", "Obróć przedramię na zewnątrz.", "Wróć powoli."],
    dosage: "3 × 12", contra: "Klikanie z bólem — lżejsza guma.",
    video: 'https://www.youtube.com/watch?v=y8WKcz0vqzg', videoLabel: 'Rotacja zewnętrzna z gumą — MGH' },
  { id: "pec-door", yt: '069o76BafTk', area: "Bark", name: "Rozciąganie klatki przy futrynie",
    goal: "Postawa, miejsce dla stożka rotatorów.",
    steps: ["Przedramiona na futrynie, krok w przód.", "Poczuj rozciąganie z przodu barków.", "Przytrzymaj 30 s × 3."],
    dosage: "3 × 30 s", contra: "Drętwienie rąk — poluzuj.",
    video: 'https://www.youtube.com/watch?v=069o76BafTk', videoLabel: 'Doorway Pec Stretch — fizjoterapeuta' },
  // ---- KRĘGOSŁUP ----
  { id: "mckenzie", yt: 'YERVv2S-vKc', area: "Kręgosłup", name: "Przeprosty McKenzie (press-up)",
    goal: "Centralizacja bólu promieniującego do nogi.",
    steps: ["Leżenie przodem, dłonie pod barkami.", "Wyprostuj łokcie, biodra na podłodze.", "Przytrzymaj 5 s, opuść. × 10."],
    dosage: "Co 2–3 h po 10 powt.", contra: "Ból ucieka w dół do stopy — STOP, zgłoś fizjo.",
    video: 'https://www.youtube.com/watch?v=YERVv2S-vKc', videoLabel: 'Cwiczenia McKenzie — Movement and Function' },
  { id: "cat-camel", yt: 'P4z-5Oz9zXE', area: "Kręgosłup", name: "Kot–wielbłąd",
    goal: "Ruchomość i odżywienie krążków.",
    steps: ["Klęk podparty.", "Zaokrąglij plecy (kot), potem wklęśnij (wielbłąd).", "Wolno, z oddechem."],
    dosage: "2 × 10", contra: "Świeży uraz — tylko bezbolesny zakres.",
    video: 'https://www.youtube.com/watch?v=P4z-5Oz9zXE', videoLabel: 'Kot-wielbłąd — Physical Therapy 101' },
  { id: "deadbug", yt: '8NBNM8haZx0', area: "Kręgosłup", name: "Dead bug (martwy robak)",
    goal: "Stabilizacja głęboka bez obciążania lędźwi.",
    steps: ["Leżenie, ręce do sufitu, biodra i kolana 90°.", "Opuść przeciwną rękę i nogę.", "Wróć, zmień stronę. Plecy płasko."],
    dosage: "3 × 8 na stronę", contra: "Ból lędźwi — mniejszy zakres.",
    video: 'https://www.youtube.com/watch?v=8NBNM8haZx0', videoLabel: 'Dead Bug — ChoosePT' },
  { id: "birddog", yt: 'k38qxElrq28', area: "Kręgosłup", name: "Bird dog (ptak–pies)",
    goal: "Stabilizacja + pośladek w wyproście.",
    steps: ["Klęk podparty.", "Wyciągnij przeciwną rękę i nogę.", "Przytrzymaj 5 s, zmień."],
    dosage: "3 × 8 na stronę", contra: "Ból barku — ćwicz samą nogą.",
    video: 'https://www.youtube.com/watch?v=k38qxElrq28', videoLabel: 'Bird Dog — poprawna forma' },
  // ---- ŻUCHWA ----
  { id: "rocabado", yt: '0WDIpGkDm6A', area: "Żuchwa", name: "Kontrolowane otwieranie (Rocabado)",
    goal: "Stabilny tor ruchu żuchwy, mniej klikania.",
    steps: ["Język na podniebieniu za górnymi zębami.", "Otwieraj usta trzymając język w miejscu.", "5 s × 6 powt., 6× dziennie."],
    dosage: "6 × 6 dziennie", contra: "Blokowanie żuchwy — nie forsuj.",
    video: 'https://www.youtube.com/watch?v=0WDIpGkDm6A', videoLabel: 'Rocabado 6x6 — BodyOne PT' },
  { id: "chin-tuck", yt: 'vhFGQxDVzF8', area: "Żuchwa", name: "Cofanie brody + korekcja postawy",
    goal: "Odciążenie szyi i żwaczy przy pracy siedzącej.",
    steps: ["Siedź prosto, wzrok przed siebie.", "Cofnij brodę jak „drugi podbródek”.", "Przytrzymaj 5 s × 10."],
    dosage: "Co 1–2 h przy biurku", contra: "Zawroty głowy — mniejszy zakres.",
    video: 'https://www.youtube.com/watch?v=vhFGQxDVzF8', videoLabel: 'Chin Tucks — Physio REHAB' },
  // ---- SKOKOWY ----
  { id: "calf-raise", yt: 'HmgXnST4Mdw', area: "Staw skokowy", name: "Wspięcia na palce",
    goal: "Łydka i stabilność kostki po skręceniu.",
    steps: ["Stanie przy ścianie.", "Wspięcie 2 s, opuszczanie 3 s.", "Progresja: jedna noga."],
    dosage: "3 × 12", contra: "Ostry ból ścięgna Achillesa — izometria zamiast dynamiki.",
    video: 'https://www.youtube.com/watch?v=HmgXnST4Mdw', videoLabel: 'Wspięcia — progresja, Physio REHAB' },
  { id: "alphabet", yt: 'dpfkCmhtg6I', area: "Staw skokowy", name: "Alfabet stopą",
    goal: "Ruchomość kostki w odciążeniu.",
    steps: ["Siad, noga w powietrzu.", "„Pisz” stopą litery A–Z.", "Wolno, pełny zakres."],
    dosage: "1 alfabet × 2 dziennie", contra: "Świeży uraz z obrzękiem — tylko bez bólu.",
    video: 'https://www.youtube.com/watch?v=dpfkCmhtg6I', videoLabel: 'Alfabet stopą — Baptist Health' }
];
